name: lolisnatcher
description: Booru Client with the ability to batch download Images.
publish_to: none

version: 2.5.1+5214 # remember to update the values in constants.dart->updateInfo after changing them here

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: 3.44.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  alice_lightweight: ^3.10.0
  app_links: ^7.2.0
  auto_size_text_plus: ^3.0.2
  calendar_date_picker2: ^3.0.0
  chewie: ^1.14.1
  clipboard: # ^3.0.14
    git:
      url: https://github.com/dongfengweixiao/flutter_clipboard.git
      ref: 6f8dce7b71396b713ab3d71cb20a04967c5458fd
  collection: ^1.19.1
  country_flags: ^4.1.2
  crypto: ^3.0.7
  device_info_plus: ^13.2.0
  dio: ^5.10.0
  dio_http2_adapter: ^2.7.1
  duration: ^4.0.3
  dynamic_color: ^1.8.1
  equatable: ^2.0.8
  external_video_player_launcher: ^0.0.3
  fading_edge_scrollview: ^4.1.1
  fast_marquee:
    git:
      url: https://github.com/NANI-SORE/fast_marquee.git
      ref: 828e79014ed5fd73062d6a24db14b6c114ac175b # master - forked to add richtext
  flash: ^3.1.1
  flex_color_picker: ^3.8.0
  flutter_avif: ^3.1.0
  flutter_displaymode: ^0.7.0
  flutter_html: ^3.0.0
  flutter_inappwebview: ^6.2.0-beta.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_linkify: ^6.0.0
  flutter_secure_storage: ^10.3.1
  flutter_socks_proxy:
    git:
      url: https://github.com/jiangtian616/socks_proxy
      ref: 52759af6c6b245db4ba5bfa9ccc64d74f3ceb2fb
  font_awesome_flutter: ^11.0.0
  fpdart: ^1.2.0
  fvp: ^0.37.3
  get_it: ^9.2.1
  get: # ^5.0.0-release-candidate-9.3.2 # TODO - MOVE TO A DIFFERENT STATE MANAGEMENT SOLUTIONS
    git:
      url: https://github.com/NANI-SORE/getx.git
      ref: 1c5917ce8bd4aa024e83ff2c52d4b19ba6c1a29e # master - forked to fix import error
  google_fonts: ^8.1.0
  html: ^0.15.6
  http_proxy: # ^1.2.2
    git:
      url: https://github.com/NANI-SORE/http_proxy.git
      ref: 36a202ceec982d199acdcd717ce85436372f447d # master - forked to fix build errors and remove allowing all bad certs
  huge_listview: ^2.0.12
  image: ^4.9.1
  intl: ^0.20.2
  keyboard_actions: # ^4.2.0
    git:
      url: https://github.com/EdgarJan/flutter_keyboard_actions.git
      ref: 561a1e3b59691b1323ac104462e76216274d6bf5 # master - fork with a fix for f3.38
  lemberfpsmonitor: ^0.0.3+6
  local_auth: ^3.0.1
  material_color_utilities: ^0.13.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  native_dio_adapter: ^1.6.0 # TODO use this for http3, probably should rewrite http client use to reduce amount of created clients
  path_provider: ^2.1.6
  permission_handler: ^12.0.3
  photo_view:
    git:
      url: https://github.com/NANI-SORE/photo_view.git
      ref: 410b4c26d7b4747e88ca2227a88fe7ad707679f1 # master
  preload_page_view: ^0.2.0
  rich_text_controller: # ^3.0.1
    git:
      url: https://github.com/NANI-SORE/rich_text_controller.git
      ref: b84b371347ab4f13374c2709becaf247aec354e4 # master - forked to change IME composing style
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^13.2.0 # not used directly, but is part of some deps (i.e. alice) # TODO move to this instead of our native share code?
  slang_flutter: ^4.18.0
  slang: ^4.18.0
  sqflite_common_ffi: ^2.4.2
  sqflite: ^2.4.3
  sqlite3: ^3.3.4
  talker_dio_logger: ^5.1.17
  talker_flutter: ^5.1.17
  talker_logger: ^5.1.17
  talker: ^5.1.17
  url_launcher: ^6.3.2
  uuid: ^4.5.3
  video_player: ^2.11.1
  waterfall_flow: ^3.1.1
  xml: ^7.0.1



dependency_overrides:
  android_intent_plus: ^6.0.0
  material_color_utilities: ^0.13.0 # flutter_test conflict
  meta: ^1.18.3 # flutter_test and image conflict
  share_plus: ^13.2.0 # alice conflict
  xml: ^7.0.1 # image conflict



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.15.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0



flutter_launcher_icons:
  android: true
  image_path: "assets/images/iconFG.png"
  image_path_android: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/iconBG.png"
  adaptive_icon_foreground: "assets/images/iconFG.png"
  adaptive_icon_monochrome: "assets/images/iconMonochrome.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/drawer_icon.png
    - assets/images/loading.gif
